// Guess the number 
/*Requirements
Scanner Class: Scanner class in the `java.util package is used to get input of primitive types like int, double, etc., as well as strings. The simplest method to read input in a Java program is this one.
Math.Random(): java.lang.Math.Random() method is used to generate a random double type number greater than or equal to 0.0 and less than 1.0.
*/

import java.util.Scanner;
import java.lang.Math;

public class Guessnumber{
    
    public static void main(String[] args){
        
        //Math. random() will generate a number between 0 and 1 so we multiply the generated number by 100. 
        // This will result in a number between 0 to 99. 
        //By adding 1 answer will be in the range of 1-100.
        //A number generated by the random() method is double so the type cast(converted from one data type to another) is into an int.
        int answer = (int)(Math.random() * 100) + 1;
        
        //number of trials that the user guess 
        int num = 5;
        
        //create Scanner class to read user input
        Scanner ip = new Scanner(System.in);
        
        // TO check if the user has guessed the number
        boolean correct = false;
        
        System.out.println("I am thinking of a number between 1 and 100.");
        System.out.println("You have 5 tries to guess the number.");
        
        while(num > 0){
            
            System.out.println("Enter your guess number: ");
            int guess = ip.nextInt();
            // if the user guesses correctly, print the congratulation message and exit the program
            if(guess == answer){
                System.out.println("You guessed the number!");
                System.out.println("You win!");
                break;
            }
            // if the user guesses greater than the number, print the message and reduce the number of trials
            else if (guess > answer) {
                System.out.println("Your guess is too high.\nYou have " + (num - 1) + " tries left.");
                num--;
            }
            // if the user guesses less than the number, print the message and reduce the number of trials
            else {
                System.out.println("Your guess is too low.\nYou have " + (num - 1) + " tries left.");
            }
            // after each trial decrease the number of trials by 1
            num--;
            
        }
        
        while(num == 0){
            // if the user has run out of trials and did not guess the right number then print the message and exit the program
            if (correct == false) {
                System.out.println("You ran out of tries.\nYou lose!");
                break;
            }
        }
        
    }
}